tamm-cci/carmm

carmm/analyse/neighbours.py, carmm/analyse/planes.py, examples/analyse_bonds.py, examples/analyse_neighbours.py, examples/analyse_neighbours_cn_surface_layers.py
=> Tidying some things

carmm/analyse/forces.py, examples/analyse_forces.py
This should stop me from breaking Hawk again.
=> Now correctly consider constraints for forces convergence check

carmm/build/unwrap.py, examples/build_unwrap.py
Added unwrapping of molecules in periodic cell based on minimal spanning tree
=> Unwrap molecule in periodic cell

carmm/build/unwrap.py
Added anchor_atom_index parameter for generality
=> Add anchor_atom_index parameter for unwrap function

carmm/run/workflows/react.py
Mullike charge analysis via sockets called FHI-aims for forces calculation
=> ReactAims fix unnecessary force calculations

carmm/analyse/molecules.py
=> Revert "changes to determine molecule symbols"

.github/workflows/main.yml, carmm/run/workflows/react.py, examples/run_workflows_ReactAims.py
- ML tests (MLNEB + AIDNEB) disabled in dry_run, MLNEB fails in CI-test while passing locally.
=> Bringing CI-test back to working condition

.github/workflows/lint.yml, .github/workflows/main.yml, examples/run_workflows_ReactAims.py
Checking the style of commits to up my game
=> React aims documentation

.github/workflows/lint.yml, .github/workflows/main.yml, examples/run_workflows_ReactAims.py
=> Linter test

examples/analyse_forces.py
Just correcting an obsolete comment - testing use of branches from PyCharmm
=> Updated comment in testing as obsolete.

carmm/analyse/vibrations.py, examples/analyse_vib_analysis.py
added class plot_vibration_data
=> updated vibrations

carmm/run/aims_path.py
Adds the HAWK AMD to the HPC list for reactaims.
=> React aims HAWK-AMD

carmm/build/adsorbate_placer.py, carmm/build/adsorbate_placer_gui.py, examples/build_adsorbate_place_and_rotate.py
Re-work of Place and Rotation - is now an object based code. Performs placement based on lone pairs (up to two). Also introduced Tkinter based GUI for rotating adsorbates for ease of use.
=> Rotate and Place GUI

carmm/build/adsorbate_placer.py
Using the natural_cutoffs multiplier
To help with systems containing close atoms.
=> Added a cutoff radius multiplier to neighbour functions

carmm/build/adsorbate_placer.py, carmm/build/adsorbate_placer_gui.py
Added some documentation to rotation box and changed some global variable names to safer names.
=> Document RotationBox

carmm/build/adsorbate_placer.py
Fixed some slopp variable names
=> Fix RotationBox Bug

examples/analyse_mulliken_difference.py
This file takes the post-adsorption, pre-adsorption, and adsorbate (optional) mulliken charge and returns the difference between them.
=> Calculating difference between mulliken charges

AUTHORS.md
The smallest change possible but it bothered me.
=> Update AUTHORS.md - oxford comma

carmm/analyse/angles.py
=> Addressed a minor doc issue

.github/workflows/linter.yml, .github/workflows/main.yml
Update to run on all branches.
=> Update yml files

carmm/run/aims_calculator.py, carmm/run/workflows/react.py, examples/analyse_counterpoise.py, examples/run_aims.py, examples/run_workflows_ReactAims.py
fhi_calc.parameters was a Parameter object with methods such as "write". Forcing it to be a dictionary causes bugs with ase 3.22
=> Fix some bugs in workflow

carmm/analyse/planes.py
=> Minor documentation improvements

.github/workflows/linter.yml, .github/workflows/main.yml, .gitignore, carmm/build/slab_consistent_bulk_generator.py, examples/build_slab_consistent_bulk.py
Testing the compatibility of the already available functions within carmm. Use one of old scripts as a test change and added some comments to it!!
=> Changed the main.yml file to specifically install ase version 3.24. 

.github/workflows/linter.yml, .github/workflows/main.yml, examples/utils_povray_render.py
Test comment added to main.yml file. This is to see why CI test is failing with Python 3.10 with some very weird errors
=> CI test failure with Python 3.10
